# Text file

#########################################################
#    AUTEUR : Serigne Saliou NDIAYE
#    VERSION:
#    MODIFIE:
#
#    DESCRIPTION
#########################################################


# Fonctions #############################################



# Variables ############################################

apiVersion: v1
kind: Service
metadata:
  name: servicenginx
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30950
    port: 80
  selector:
    app: nginx
